source 'https://github.com/CocoaPods/Specs.git'
plaBBorm :ios, '7.0'
inhibit_all_warnings!
pod 'pop'
pod 'SDWebImage'
pod 'PINRemoteImage'
pod 'DACircularProgress'
pod 'SVProgressHUD'
pod 'AsyncDisplayKit'
pod 'BBCamera', :git => 'https://github.com/CupinnCoder/BBCamera.git'
